#ifndef THERMOMETER_GLOBAL_H
#define THERMOMETER_GLOBAL_H

#if defined(THERMOMETER_LIBRARY)
    #define THERMOMETER_EXPORT Q_DECL_EXPORT
#else
    #define THERMOMETER_EXPORT Q_DECL_IMPORT
#endif

#endif // THERMOMETER_GLOBAL_H
